### ISSUE TITLE
will this work with cpanel ? centos 7

### ISSUE THREAD

**Issue by spirogg** [zorrigas/ffmpeg-build#1]
will this work with cpanel ? centos 7
I've tried 5 times of other autoinstallers or just to compile my own but never finish errors so thats why i ask if this will work with cpanel/whm and CENTOS 7.4 kvm ?
i guess i will try but if i cant get it to work can you help me install it on my vps ?

thanks

Spiro

**Comment by zorrigas** [comment]
Yes, is working on my whm vps :+1:
